[package]
name = "telos"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
log = "0.4.27"
pretty_env_logger = "0.5.0"
regex = "1.11.1"
teloxide = { version = "0.16.0", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
